export const t = {
  en: {
    translation: {
      title: {
        welcome: "Welcome",
        welcomeBack: "Welcome back",
        createAccount: "Create an Account",
        profile: "Profile",
        editProfile: "Edit profile",
        changePassword: "Change password",
        events: "Events",
        updateEvent: "Update event",
        createEvent: "Add new event",
      },
      button: {
        signIn: "Sign in",
        register: "Register",
        signOut: "Sign out",
        createAccount: "Create an account",
        create: "Create",
        forgotPassword: "Forgot password?",
        save: "Save",
        changePassword: "Change password",
        editProfile: "Edit profile",
        update: "Update",
        deleteEvent: "Delete event",
      },
      label: {
        name: "Name",
        email: "E-Mail",
        password: "Password",
        newPassword: "New password",
        repeatNewPassword: "Repeat new password",
        currentPassword: "Current password",
        repeatPassword: "Repeat password",
        hiddenPassword: "********",
        newEvent: "New event",
        title: "Title",
        date: "Date",
        time: "Time",
        noEvents: "No events for selected date",
      },
      message: {
        loginFailed: "Login failed",
        passwordsMissmatch: "Passwords don't match",
        passwordChangeFailed: "Error changing password",
        profileUpdateFailed: "Error updating profile",
        deviceNotSecure:
          "Your device is not secure enough. Try changing profile on a different device (e.g. with fingerprint or face scan support)",
        weakSecurity:
          "Your device is not secure enough. Try securing your device with a fingerprint, face scan, PIN, pattern, etc.",
        biometricsPrompt: "Authenticate with biometrics to edit profile",
        authorizationFailed: "Error while authorizing the change",
        emailEmpty: "You must enter an email",
        passwordEmpty: "You must enter a password",
        titleEmpty: "Title cannot be empty",
        eventUpdateSuccess: "Event updated!",
        eventCreateSuccess: "Event created!",
        error: "An error occurred",
      },
    },
  },
};
